from django.core.mail import send_mail
from django.conf import settings
from django.utils import timezone
from datetime import timedelta
from employees.models import LeaveRequest, Employee

def generate_daily_report():
    """Generate a beautiful daily report of pending leave requests"""
    today = timezone.now().date()
    pending_requests = LeaveRequest.objects.filter(status='PENDING')
    
    # تنسيق التاريخ
    date_formatted = today.strftime("%A, %d %B %Y")  # Saturday, 09 August 2026
    
    # تصميم التقرير
    report = "=" * 60 + "\n"
    report += f"📋 DAILY LEAVE REPORT\n"
    report += f"📅 {date_formatted}\n"
    report += "=" * 60 + "\n\n"
    
    # إحصائيات
    total = pending_requests.count()
    report += f"📊 Total Pending: {total}\n"
    report += f"⏰ Generated at: {timezone.now().strftime('%H:%M:%S')}\n"
    report += "-" * 60 + "\n\n"
    
    if total == 0:
        report += "🎉 No pending requests! All leaves are approved.\n"
        report += "🌟 Great job team!\n"
    else:
        # تفاصيل الطلبات
        report += "📌 DETAILED REQUESTS:\n\n"
        
        for idx, req in enumerate(pending_requests, 1):
            # أيام الإجازة
            days = (req.end_date - req.start_date).days + 1
            
            report += f"{idx}. {req.employee.user.first_name} {req.employee.user.last_name}\n"
            report += f"   🏢 Department: {req.employee.department}\n"
            report += f"   📂 Type: {req.get_leave_type_display()}\n"
            report += f"   📅 From: {req.start_date.strftime('%d/%m/%Y')} → {req.end_date.strftime('%d/%m/%Y')}\n"
            report += f"   ⏳ Duration: {days} days\n"
            report += f"   💬 Reason: {req.reason}\n"
            
            # إضافة أيقونة حسب النوع
            if req.leave_type == 'EMERGENCY':
                report += "   🚨 URGENT\n"
            elif days > 5:
                report += "   ⚠️ Long leave (needs attention)\n"
            
            report += "\n"
        
        # نصائح
        report += "-" * 60 + "\n"
        report += "💡 MANAGER TIPS:\n"
        
        urgent = pending_requests.filter(leave_type='EMERGENCY')
        if urgent.exists():
            report += f"   ⚡ {urgent.count()} urgent requests need immediate attention!\n"
        
        long_leaves = [r for r in pending_requests if (r.end_date - r.start_date).days + 1 > 5]
        if long_leaves:
            report += f"   📌 {len(long_leaves)} long leave requests (>5 days) require review.\n"
        
        report += f"   🤖 Check AI recommendations for assistance.\n"
    
    report += "\n" + "=" * 60 + "\n"
    report += "📧 This report is auto-generated by Leave Management System\n"
    report += f"🔗 Admin Panel: /admin\n"
    report += "=" * 60
    
    return report

def send_daily_report_email():
    """Send daily report via email (console for now)"""
    report = generate_daily_report()
    
    # For testing, we'll print to console
    print("\n" + "="*60)
    print("📧 EMAIL REPORT SENT:")
    print(report)
    print("="*60 + "\n")
    
    # In production, uncomment this:
    # send_mail(
    #     subject=f'Daily Leave Report - {timezone.now().date()}',
    #     message=report,
    #     from_email='noreply@company.com',
    #     recipient_list=['manager@company.com'],
    #     fail_silently=False,
    # )
    
    return report

def auto_approve_emergency_requests():
    """Auto-approve emergency leave requests if less than 2 days"""
    emergency_requests = LeaveRequest.objects.filter(
        status='PENDING',
        leave_type='EMERGENCY'
    )
    
    approved_count = 0
    for req in emergency_requests:
        if req.days_count <= 2:
            req.status = 'APPROVED'
            req.approval_date = timezone.now()
            req.save()
            approved_count += 1
    
    return approved_count

def process_weekly_summary():
    """Generate weekly summary of all leave requests"""
    today = timezone.now().date()
    week_ago = today - timedelta(days=7)
    
    requests = LeaveRequest.objects.filter(created_at__date__gte=week_ago)
    
    summary = f"📊 Weekly Leave Summary - {today}\n"
    summary += "=" * 50 + "\n"
    summary += f"Total Requests: {requests.count()}\n"
    summary += f"Pending: {requests.filter(status='PENDING').count()}\n"
    summary += f"Approved: {requests.filter(status='APPROVED').count()}\n"
    summary += f"Rejected: {requests.filter(status='REJECTED').count()}\n"
    
    return summary